module.exports = {
  dus: {
    name: 'DUS',
    nameAr: 'امتحان التخصص في طب الأسنان (DUS)',
    nameTr: 'DUS',
    emoji: '🦷',
    color: 'from-slate-400 to-slate-600',
    questions: [
      { "q": "Which doctor treats the teeth and mouth?", "qAr": "أي طبيب يعالج الأسنان والفم؟", "qTr": "Diş ve ağız hastalıklarını hangi doktor tedavi eder?", "options": ["Dentist", "Ophthalmologist", "Cardiologist", "Physiotherapist"], "optionsAr": ["طبيب الأسنان", "طبيب العيون", "طبيب القلب", "أخصائي العلاج الطبيعي"], "optionsTr": ["Diş hekimi", "Göz doktoru", "Kardiyolog", "Fizyoterapist"], "correct": 0 },
      { "q": "How many teeth does an adult human normally have?", "qAr": "كم عدد أسنان الإنسان البالغ عادةً؟", "qTr": "Yetişkin bir insanda normalde kaç diş bulunur?", "options": ["20", "28", "32", "36"], "optionsAr": ["20", "28", "32", "36"], "optionsTr": ["20", "28", "32", "36"], "correct": 2 },
      { "q": "Which is the hardest substance in the human body?", "qAr": "ما هي أقسى مادة في جسم الإنسان؟", "qTr": "İnsan vücudundaki en sert madde hangisidir?", "options": ["Bone", "Enamel", "Cartilage", "Tendon"], "optionsAr": ["العظم", "مينا الأسنان", "الغضروف", "الوتر"], "optionsTr": ["Kemik", "Diş minesi", "Kıkırdak", "Tendon"], "correct": 1 },
      { "q": "Which tool does a dentist use to examine the back of the mouth?", "qAr": "ما الأداة التي يستخدمها طبيب الأسنان لفحص الجزء الخلفي من الفم؟", "qTr": "Diş hekimi ağzın arkasını incelemek için hangi aleti kullanır?", "options": ["Dental mirror", "Stethoscope", "Ophthalmoscope", "Hammer"], "optionsAr": ["مرآة الأسنان", "السماعة الطبية", "منظار العين", "المطرقة"], "optionsTr": ["Diş aynası", "Stetoskop", "Oftalmoskop", "Çekiç"], "correct": 0 },
      { "q": "What is the main cause of tooth decay?", "qAr": "ما السبب الرئيسي لتسوس الأسنان؟", "qTr": "Diş çürümesinin başlıca nedeni hangisidir?", "options": ["Plaque and sugar", "Cold weather", "Loud music", "Sunlight"], "optionsAr": ["الترسبات والسكر", "البرد", "الموسيقى الصاخبة", "أشعة الشمس"], "optionsTr": ["Plak ve şeker", "Soğuk hava", "Yüksek sesli müzik", "Güneş ışığı"], "correct": 0 },
      { "q": "How many times a day should you ideally brush your teeth?", "qAr": "كم مرة يومياً يُفضَّل أن تنظف أسنانك؟", "qTr": "Dişlerinizi günde kaç kez fırçalamalısınız?", "options": ["Once a day", "Twice a day", "Once a week", "Once a month"], "optionsAr": ["مرة واحدة يومياً", "مرتين يومياً", "مرة في الأسبوع", "مرة في الشهر"], "optionsTr": ["Günde bir kez", "Günde iki kez", "Haftada bir kez", "Ayda bir kez"], "correct": 1 },
      { "q": "What is the visible part of a tooth above the gum called?", "qAr": "ماذا يُسمى الجزء الظاهر من السن فوق اللثة؟", "qTr": "Dişin diş eti üzerinde görünen kısmına ne denir?", "options": ["Root", "Crown", "Pulp", "Neck"], "optionsAr": ["الجذر", "التاج", "اللب", "العنق"], "optionsTr": ["Kök", "Kuron", "Pulpa", "Boyun"], "correct": 1 },
      { "q": "How many milk (baby) teeth does a child have?", "qAr": "كم عدد الأسنان اللبنية عند الطفل؟", "qTr": "Bir çocuğun kaç süt dişi vardır?", "options": ["10", "20", "28", "32"], "optionsAr": ["10", "20", "28", "32"], "optionsTr": ["10", "20", "28", "32"], "correct": 1 },
      { "q": "Which part of the tooth contains nerves and blood vessels?", "qAr": "أي جزء من السن يحتوي على الأعصاب والأوعية الدموية؟", "qTr": "Dişin sinir ve damarları içeren kısmı hangisidir?", "options": ["Pulp", "Enamel", "Crown", "Cementum"], "optionsAr": ["اللب", "المينا", "التاج", "الأسمنت"], "optionsTr": ["Pulpa", "Mine", "Kuron", "Sement"], "correct": 0 },
      { "q": "A routine visit to the dentist for checking is called a ———.", "qAr": "الزيارة المنتظمة لطبيب الأسنان للفحص تُسمى ———.", "qTr": "Diş hekimine kontrol için yapılan rutin ziyarete ——— denir.", "options": ["check-up", "surgery", "gym", "internship"], "optionsAr": ["فحص دوري", "عملية جراحية", "ناد رياضي", "تدريب"], "optionsTr": ["kontrol (check-up)", "ameliyat", "spor salonu", "staj"], "correct": 0 },
      { "q": "Fluoride is added to toothpaste mainly to ———.", "qAr": "يُضاف الفلورايد إلى معجون الأسنان أساساً من أجل ———.", "qTr": "Florür diş macununa en çok ——— için eklenir.", "options": ["strengthen tooth enamel", "make it colourful", "add flavour", "remove stains easily"], "optionsAr": ["تقوية مينا الأسنان", "إضفاء اللون", "إضافة النكهة", "إزالة البقع بسهولة"], "optionsTr": ["Diş minesini güçlendirmek", "Renk katmak", "Lezzet vermek", "Lekeleri kolay çıkarmak"], "correct": 0 },
      { "q": "What should you do after a tooth extraction?", "qAr": "ماذا يجب أن تفعل بعد خلع السن؟", "qTr": "Diş çekildikten sonra ne yapmalısınız?", "options": ["Press gauze on the wound", "Rinse with hot water", "Run fast", "Eat hard food"], "optionsAr": ["الضغط بشاش على الجرح", "المضمضة بماء ساخن", "الجري بسرعة", "أكل طعام صلب"], "optionsTr": ["Yara üzerine bezle basınç uygulamak", "Sıcak suyla çalkalamak", "Hızlı koşmak", "Sert yiyecek yemek"], "correct": 0 },
      { "q": "Which exam does a dentist take to specialise in Turkey?", "qAr": "ما الامتحان الذي يؤديه طبيب الأسنان للتخصص في تركيا؟", "qTr": "Türkiye'de diş hekiminin uzmanlaşmak için girdiği sınav hangisidir?", "options": ["TUS", "DUS", "EUS", "YKS"], "optionsAr": ["TUS", "DUS", "EUS", "YKS"], "optionsTr": ["TUS", "DUS", "EUS", "YKS"], "correct": 1 },
      { "q": "Which of these drinks is the most harmful to teeth?", "qAr": "أي من هذه المشروبات هو الأكثر ضرراً للأسنان؟", "qTr": "Hangisi dişlere en zararlı içecektir?", "options": ["Sugary soda", "Water", "Milk", "Tea without sugar"], "optionsAr": ["المشروبات الغازية السكرية", "الماء", "الحليب", "الشاي دون سكر"], "optionsTr": ["Şekerli gazlı içecek", "Su", "Süt", "Şekersiz çay"], "correct": 0 },
      { "q": "Gum disease mainly affects the ———.", "qAr": "أمراض اللثة تؤثر أساساً على ———.", "qTr": "Diş eti hastalığı en çok ——— etkiler.", "options": ["gums (gingiva)", "eyelashes", "nails", "hair"], "optionsAr": ["اللثة", "الرموش", "الأظافر", "الشعر"], "optionsTr": ["Diş etlerini", "Kirpikleri", "Tırnakları", "Saçları"], "correct": 0 }
    ]
  },
  eus: {
    name: 'EUS',
    nameAr: 'امتحان التخصص في الصيدلة (EUS)',
    nameTr: 'EUS',
    emoji: '💊',
    color: 'from-green-500 to-emerald-700',
    questions: [
      { "q": "Which professional prepares and dispenses medicines?", "qAr": "أي مختص يحضّر الأدوية ويصرفها؟", "qTr": "İlaçları hazırlayan ve dağıtan meslek uzmanı hangisidir?", "options": ["Pharmacist", "Engineer", "Pilot", "Chef"], "optionsAr": ["الصيدلي", "المهندس", "الطيار", "الطباخ"], "optionsTr": ["Eczacı", "Mühendis", "Pilot", "Aşçı"], "correct": 0 },
      { "q": "Where do people buy their medicines in Turkey?", "qAr": "أين يشتري الناس أدويتهم في تركيا؟", "qTr": "Türkiye'de insanlar ilaçlarını nereden satın alır?", "options": ["Pharmacy", "Fish market", "Bookshop", "Pet store"], "optionsAr": ["من الصيدلية", "من سوق السمك", "من المكتبة", "من متجر الحيوانات"], "optionsTr": ["Eczaneden", "Balık pazarından", "Kitapçıdan", "Pet shop'tan"], "correct": 0 },
      { "q": "What is the doctor's written order for a medicine called?", "qAr": "ماذا يُسمى الأمر الكتابي من الطبيب للحصول على دواء؟", "qTr": "Doktorun ilaç için yazdığı yazılı emir ne olarak adlandırılır?", "options": ["Prescription", "Invoice", "Menu", "Ticket"], "optionsAr": ["الوصفة الطبية", "الفاتورة", "القائمة", "التذكرة"], "optionsTr": ["Reçete", "Fatura", "Menü", "Bilet"], "correct": 0 },
      { "q": "Which of these medicine forms is taken by mouth as a liquid?", "qAr": "أي من هذه الأشكال الدوائية يؤخذ عن طريق الفم كسائل؟", "qTr": "Hangi ilaç formu ağız yoluyla sıvı olarak alınır?", "options": ["Syrup", "Tablet", "Cream", "Suppository"], "optionsAr": ["الشراب", "الحبة", "المرهم", "التحميلة"], "optionsTr": ["Şurup", "Tablet", "Krem", "Supozituvar"], "correct": 0 },
      { "q": "Antibiotics are used against ———.", "qAr": "تُستخدم المضادات الحيوية ضد ———.", "qTr": "Antibiyotikler ——— karşı kullanılır.", "options": ["bacteria", "snow", "lightning", "gravity"], "optionsAr": ["البكتيريا", "الثلج", "البرق", "الجاذبية"], "optionsTr": ["bakterilere", "kara", "yıldırıma", "yer çekimine"], "correct": 0 },
      { "q": "Medicines should always be stored ———.", "qAr": "يجب دائماً حفظ الأدوية ———.", "qTr": "İlaçlar her zaman ——— saklanmalıdır.", "options": ["out of children's reach", "in the kitchen sink", "near flames", "in the fridge door"], "optionsAr": ["بعيداً عن متناول الأطفال", "في حوض المطبخ", "قرب النار", "في باب الثلاجة"], "optionsTr": ["Çocukların ulaşamayacağı yerde", "Mutfak evyesinde", "Ateşe yakın", "Buzdolabı kapağında"], "correct": 0 },
      { "q": "What do the letters 'Rx' typically stand for on prescriptions?", "qAr": "ماذا يُشير عادةً الحرفان Rx على الوصفات الطبية؟", "qTr": "Reçetelerdeki 'Rx' sembolü neyi ifade eder?", "options": ["Take (medicine)", "Reject", "Return", "Repeat"], "optionsAr": ["يؤخذ (الدواء)", "يرفض", "يعيد", "يكرر"], "optionsTr": ["Al (ilaç reçetesi)", "Reddet", "İade et", "Tekrar et"], "correct": 0 },
      { "q": "Pharmacology is the science that studies ———.", "qAr": "علم الصيدلة هو العلم الذي يدرس ———.", "qTr": "Farmakoloji ——— inceleyen bilim dalıdır.", "options": ["the effects of drugs", "planets", "fossils", "weather"], "optionsAr": ["تأثيرات الأدوية", "الكواكب", "الأحافير", "الطقس"], "optionsTr": ["İlaçların etkilerini", "Gezegenleri", "Fosilleri", "Havayı"], "correct": 0 },
      { "q": "Which of the following is an injectable medicine form?", "qAr": "أي مما يلي شكل دوائي يُعطى عن طريق الحقن؟", "qTr": "Hangisi enjeksiyon yoluyla verilen ilaç formudur?", "options": ["Ampoule", "Lozenge", "Capsule", "Gel strip"], "optionsAr": ["الأمبولة", "القرص المصّ", "الكبسولة", "شريط الجل"], "optionsTr": ["Ampul", "Pastil", "Kapsül", "Jel bant"], "correct": 0 },
      { "q": "What is the tiny plan for a drug's schedule, printed on the pack, called?", "qAr": "ما اسم الجدول الصغير على علبة الدواء الذي يبين مواعيد تناوله؟", "qTr": "İlaç kutusundaki doz zaman cetveli ne olarak bilinir?", "options": ["Blister calendar", "Car manual", "Train map", "League table"], "optionsAr": ["تقويم الأقراص (بلاستر)", "دليل السيارة", "خريطة القطار", "جدول الترتيب"], "optionsTr": ["Blister takvim", "Araç kılavuzu", "Tren haritası", "Puan tablosu"], "correct": 0 },
      { "q": "Expired medicines should be ———.", "qAr": "يجب أن تكون الأدوية منتهية الصلاحية ———.", "qTr": "Son kullanma tarihi geçmiş ilaçlar ———.", "options": ["returned to the pharmacy for safe disposal", "given to animals", "kept forever", "sold online"], "optionsAr": ["تُرجع إلى الصيدلية للتخلص الآمن", "تُعطى للحيوانات", "تُحفظ للأبد", "تُباع عبر الإنترنت"], "optionsTr": ["Güvenli imha için eczaneye iade edilir", "Hayvanlara verilir", "Sonsuza kadar saklanır", "Çevrim içi satılır"], "correct": 0 },
      { "q": "Which of these is a well-known medicinal plant?", "qAr": "أي مما يلي نبات طبي مشهور؟", "qTr": "Hangisi bilinen bir tıbbi bitkidir?", "options": ["Chamomile", "Cactus only", "Moss", "Seaweed only"], "optionsAr": ["البابونج", "الصبار فقط", "الطحالب", "الأعشاب البحرية فقط"], "optionsTr": ["Papatya", "Sadece kaktüs", "Kara yosunu", "Sadece deniz yosunu"], "correct": 0 },
      { "q": "A 'side effect' of a medicine means ———.", "qAr": "الآثار الجانبية للدواء تعني ———.", "qTr": "İlacın 'yan etkisi' ——— anlamına gelir.", "options": ["an unwanted effect", "a free gift", "a new taste", "a stronger pack"], "optionsAr": ["تأثير غير مرغوب فيه", "هدية مجانية", "نكهة جديدة", "علبة أكبر"], "optionsTr": ["istenmeyen bir etki", "ücretsiz bir hediye", "yeni bir tat", "daha büyük kutu"], "correct": 0 },
      { "q": "What is the ratio marked as 'mg' on medicine packs?", "qAr": "ما الذي يُعبَّر عنه بالرمز mg على علب الأدوية؟", "qTr": "İlaç kutularındaki 'mg' hangi birimi ifade eder?", "options": ["Dose weight in milligrams", "Price", "Volume in litres", "Expiry in months"], "optionsAr": ["وزن الجرعة بالمليغرام", "السعر", "الحجم باللتر", "الصلاحية بالأشهر"], "optionsTr": ["Miligram cinsinden doz ağırlığı", "Fiyat", "Litre cinsinden hacim", "Ay cinsinden süre"], "correct": 0 },
      { "q": "Which exam does a pharmacist take to specialise in Turkey?", "qAr": "ما الامتحان الذي يؤديه الصيدلي للتخصص في تركيا؟", "qTr": "Türkiye'de eczacının uzmanlaşmak için girdiği sınav hangisidir?", "options": ["EUS", "LGS", "YKS", "KPSS"], "optionsAr": ["EUS", "LGS", "YKS", "KPSS"], "optionsTr": ["EUS", "LGS", "YKS", "KPSS"], "correct": 0 }
    ]
  },
  hmgs: {
    name: 'HMGS',
    nameAr: 'امتحان دخول المهن القانونية (HMGS)',
    nameTr: 'HMGS',
    emoji: '⚖️',
    color: 'from-stone-400 to-neutral-600',
    questions: [
      { "q": "Which professional defends clients in court?", "qAr": "أي مهني يدافع عن الموكلين أمام المحكمة؟", "qTr": "Mahkemede müvekkilleri hangi meslek mensubu savunur?", "options": ["Lawyer", "Pilot", "Chef", "Guard"], "optionsAr": ["المحامي", "الطيار", "الطباخ", "الحارس"], "optionsTr": ["Avukat", "Pilot", "Aşçı", "Güvenlik"], "correct": 0 },
      { "q": "Who presides over the court and decides the cases?", "qAr": "من يترأس المحكمة ويحكم في القضايا؟", "qTr": "Mahkemeye başkanlık eden ve davalara hükmeden kimdir?", "options": ["Judge", "Postman", "Vendor", "Driver"], "optionsAr": ["القاضي", "ساعي البريد", "البائع", "السائق"], "optionsTr": ["Hâkim", "Postacı", "Satıcı", "Şoför"], "correct": 0 },
      { "q": "Which body makes laws in Turkey?", "qAr": "ما الجهة التي تسنّ القوانين في تركيا؟", "qTr": "Türkiye'de yasaları hangi kurum yapar?", "options": ["Grand National Assembly", "The Grand Bazaar", "The Stadium", "The Market Board"], "optionsAr": ["الجمعية الوطنية الكبرى", "البازار الكبير", "الملعب", "مجلس السوق"], "optionsTr": ["Türkiye Büyük Millet Meclisi", "Kapalı Çarşı", "Stadyum", "Market Kurulu"], "correct": 0 },
      { "q": "Which is the highest court of constitutional review in Turkey?", "qAr": "ما أعلى محكمة للمراجعة الدستورية في تركيا؟", "qTr": "Türkiye'de anayasal denetimin en yüksek mahkemesi hangisidir?", "options": ["Constitutional Court", "Traffic Court", "Family Court", "Labour Court"], "optionsAr": ["المحكمة الدستورية", "محكمة المرور", "محكمة الأسرة", "محكمة العمل"], "optionsTr": ["Anayasa Mahkemesi", "Trafik Mahkemesi", "Aile Mahkemesi", "İş Mahkemesi"], "correct": 0 },
      { "q": "What is the Constitution?", "qAr": "ما هو الدستور؟", "qTr": "Anayasa nedir?", "options": ["The fundamental law of the state", "A shopping list", "A sports rulebook", "A cooking recipe"], "optionsAr": ["القانون الأساسي للدولة", "قائمة تسوق", "قواعد رياضية", "وصفة طبخ"], "optionsTr": ["Devletin temel yasası", "Bir alışveriş listesi", "Bir spor kuralı", "Bir yemek tarifi"], "correct": 0 },
      { "q": "Who brings criminal charges on behalf of the state?", "qAr": "من يتولى الاتهام الجنائي نيابة عن الدولة؟", "qTr": "Devlet adına ceza davası açan kimdir?", "options": ["Prosecutor", "Pharmacist", "Baker", "Mosque imam"], "optionsAr": ["النائب العام (المدعي)", "الصيدلي", "الخباز", "إمام المسجد"], "optionsTr": ["Savcı", "Eczacı", "Fırıncı", "İmam"], "correct": 0 },
      { "q": "A person accused of a crime in court is called the ———.", "qAr": "مَن هو الشخص المتهم بارتكاب جريمة في المحكمة؟", "qTr": "Mahkemede bir suçla itham edilen kişiye ne denir?", "options": ["Defendant", "Witness", "Audience", "Referee"], "optionsAr": ["المدعى عليه", "الشاهد", "الجمهور", "الحكم"], "optionsTr": ["Sanık", "Tanık", "Seyirci", "Hakem"], "correct": 0 },
      { "q": "What does a witness do in court?", "qAr": "ماذا يفعل الشاهد في المحكمة؟", "qTr": "Mahkemede tanık ne yapar?", "options": ["Testifies about what they saw", "Sells tickets", "Keeps silence", "Sweeps the floor"], "optionsAr": ["أداء الشهادة عن ما رآه", "بيع التذاكر", "التزام الصمت", "كنس الأرضية"], "optionsTr": ["Gördükleri hakkında ifade verir", "Bilet satar", "Sessiz kalır", "Yerleri süpürür"], "correct": 0 },
      { "q": "Taking someone's property without permission is ———.", "qAr": "أخذ ممتلكات شخص دون إذن يُعد ———.", "qTr": "Birinin malını izinsiz almak ——— dir.", "options": ["theft", "a haircut", "charity", "exercise"], "optionsAr": ["سرقة", "قصة شعر", "صدقة", "رياضة"], "optionsTr": ["hırsızlık", "saç kesimi", "bağış", "spor"], "correct": 0 },
      { "q": "At what age does a person reach full legal capacity (majority) in Turkey?", "qAr": "في أي سن يبلغ الشخص سن الرشد القانوني الكامل في تركيا؟", "qTr": "Türkiye'de kişi kaç yaşında tam ehliyete (reşit) erişir?", "options": ["18", "12", "21", "16"], "optionsAr": ["18", "12", "21", "16"], "optionsTr": ["18", "12", "21", "16"], "correct": 0 },
      { "q": "Which authority has the power to arrest a suspect in Turkey?", "qAr": "ما الجهة التي تملك سلطة توقيف المشتبه به في تركيا؟", "qTr": "Türkiye'de şüpheliyi tutuklama yetkisine sahip kurum hangisidir?", "options": ["The police", "The bakery", "The zoo", "The school"], "optionsAr": ["الشرطة", "المخبز", "حديقة الحيوان", "المدرسة"], "optionsTr": ["Polis", "Fırın", "Hayvanat bahçesi", "Okul"], "correct": 0 },
      { "q": "The principle 'innocent until proven guilty' is called ———.", "qAr": "مبدأ «بريء حتى تثبت إدانته» يُسمى ———.", "qTr": "'Suçlu olduğu kanıtlanana kadar masum' ilkesinin adı nedir?", "options": ["Presumption of innocence", "Right to vote", "Freedom of speech", "Trial by ordeal"], "optionsAr": ["افتراض البراءة", "حق التصويت", "حرية التعبير", "محنة الاختبار"], "optionsTr": ["Masumiyet karinesi", "Oy hakkı", "İfade özgürlüğü", "Çile sınavı"], "correct": 0 },
      { "q": "A written, signed statement of one's last wishes is called a ———.", "qAr": "البيان المكتوب الموقَّع حول وصية الفرد الأخيرة يُسمى ———.", "qTr": "Kişinin son isteklerini yazılı imzalı beyanına ——— denir.", "options": ["Will", "Bill", "Menu", "Map"], "optionsAr": ["الوصية", "الفاتورة", "القائمة", "الخريطة"], "optionsTr": ["Vasiyet", "Fatura", "Menü", "Harita"], "correct": 0 },
      { "q": "A contract is legally binding because ———.", "qAr": "العقد مُلزم قانونياً لأن ———.", "qTr": "Sözleşme hukuken bağlayıcıdır çünkü ———.", "options": ["it creates mutual rights and duties", "it looks beautiful", "it is printed in black", "it is long"], "optionsAr": ["يُنشئ حقوقاً والتزامات متبادلة", "شكله جميل", "مطبوع بالأسود", "طويل"], "optionsTr": ["Karşılıklı hak ve yükümlülükler doğurur", "Güzel görünür", "Siyah basılmıştır", "Uzundur"], "correct": 0 },
      { "q": "Which exam is required to enter the legal professions in Turkey?", "qAr": "ما الامتحان المطلوب لدخول المهن القانونية في تركيا؟", "qTr": "Türkiye'de hukuk mesleklerine giriş için gereken sınav hangisidir?", "options": ["HMGS", "TUS", "DUS", "EUS"], "optionsAr": ["HMGS", "TUS", "DUS", "EUS"], "optionsTr": ["HMGS", "TUS", "DUS", "EUS"], "correct": 0 }
    ]
  },
  lgs: {
    name: 'LGS',
    nameAr: 'امتحان الانتقال إلى الثانوية (LGS)',
    nameTr: 'LGS',
    emoji: '🏫',
    color: 'from-orange-500 to-red-500',
    questions: [
      { "q": "What is the name of the exam used to enter high school in Turkey?", "qAr": "ما اسم الامتحان المستخدم للالتحاق بالثانوية في تركيا؟", "qTr": "Türkiye'de liseye geçişte kullanılan sınavın adı nedir?", "options": ["LGS", "YKS", "TUS", "ALES"], "optionsAr": ["LGS", "YKS", "TUS", "ALES"], "optionsTr": ["LGS", "YKS", "TUS", "ALES"], "correct": 0 },
      { "q": "After completing 8th grade, students in Turkey move on to ———.", "qAr": "بعد إنهاء الصف الثامن، ينتقل الطلاب في تركيا إلى ———.", "qTr": "Türkiye'de 8. sınıfı bitiren öğrenciler ——— geçer.", "options": ["high school", "kindergarten", "nursery", "university doctorate"], "optionsAr": ["الثانوية", "الروضة", "الحضانة", "الدكتوراه"], "optionsTr": ["liseye", "anaokuluna", "kreşe", "doktoraya"], "correct": 0 },
      { "q": "What is the first year of high school in Turkey called?", "qAr": "ماذا يُسمى الصف الأول من الثانوية في تركيا؟", "qTr": "Türkiye'de lisenin ilk yılına ne denir?", "options": ["Grade 9", "Grade 5", "Grade 3", "Grade 12"], "optionsAr": ["الصف التاسع", "الصف الخامس", "الصف الثالث", "الصف الثاني عشر"], "optionsTr": ["9. sınıf", "5. sınıf", "3. sınıf", "12. sınıf"], "correct": 0 },
      { "q": "Which subject teaches algebra and geometry?", "qAr": "أي مادة تعلم الجبر والهندسة؟", "qTr": "Cebir ve geometriyi hangi ders öğretir?", "options": ["Mathematics", "Music", "Art", "P.E."], "optionsAr": ["الرياضيات", "الموسيقى", "الفن", "التربية البدنية"], "optionsTr": ["Matematik", "Müzik", "Resim", "Beden eğitimi"], "correct": 0 },
      { "q": "What is the process of water turning into vapour called?", "qAr": "ماذا تُسمى عملية تحول الماء إلى بخار؟", "qTr": "Suyun buharlaşması hangi kavramla ifade edilir?", "options": ["Evaporation", "Melting", "Freezing", "Condensing"], "optionsAr": ["التبخر", "الانصهار", "التجمد", "التكاثف"], "optionsTr": ["Buharlaşma", "Erime", "Donma", "Yoğuşma"], "correct": 0 },
      { "q": "Which planet is known as the Red Planet?", "qAr": "ما الكوكب المعروف بالكوكب الأحمر؟", "qTr": "Kızıl Gezegen olarak bilinen gezegen hangisidir?", "options": ["Mars", "Venus", "Jupiter", "Saturn"], "optionsAr": ["المريخ", "الزهرة", "المشتري", "زحل"], "optionsTr": ["Mars", "Venüs", "Jüpiter", "Satürn"], "correct": 0 },
      { "q": "Which of these is a renewable energy source?", "qAr": "أي مما يلي مصدر طاقة متجدد؟", "qTr": "Hangisi yenilenebilir bir enerji kaynağıdır?", "options": ["Solar energy", "Coal", "Petroleum", "Natural gas"], "optionsAr": ["الطاقة الشمسية", "الفحم", "النفط", "الغاز الطبيعي"], "optionsTr": ["Güneş enerjisi", "Kömür", "Petrol", "Doğalgaz"], "correct": 0 },
      { "q": "DNA in cells is mostly found in the ———.", "qAr": "الحمض النووي (DNA) في الخلايا يوجد غالباً في ———.", "qTr": "Hücrede DNA'nın büyük kısmı ——— bulunur.", "options": ["nucleus", "cell wall", "ribosome tip", "petal"], "optionsAr": ["النواة", "الجدار الخلوي", "الريبوسوم", "البتلة"], "optionsTr": ["çekirdekte", "hücre duvarında", "ribozomda", "taç yaprakta"], "correct": 0 },
      { "q": "Which gas do plants absorb from the air for photosynthesis?", "qAr": "ما الغاز الذي تمتصه النباتات من الهواء لأجل التمثيل الضوئي؟", "qTr": "Fotosentez için bitkiler havadan hangi gazı alır?", "options": ["Carbon dioxide", "Oxygen", "Helium", "Argon"], "optionsAr": ["ثاني أكسيد الكربون", "الأكسجين", "الهيليوم", "الأرجون"], "optionsTr": ["Karbondioksit", "Oksijen", "Helyum", "Argon"], "correct": 0 },
      { "q": "Force in the SI system is measured in ———.", "qAr": "تُقاس القوة في النظام الدولي بوحدة ———.", "qTr": "SI sisteminde kuvvet ——— ile ölçülür.", "options": ["Newtons", "Litres", "Degrees", "Volts"], "optionsAr": ["نيوتن", "اللتر", "الدرجات", "الفولت"], "optionsTr": ["Newton", "Litre", "Derece", "Volt"], "correct": 0 },
      { "q": "Which system carries blood around the body?", "qAr": "ما النظام الذي ينقل الدم في الجسم؟", "qTr": "Kanı vücutta taşıyan sistem hangisidir?", "options": ["Circulatory system", "Nervous system", "Skeletal system", "Digestive system"], "optionsAr": ["الجهاز الدوري", "الجهاز العصبي", "الجهاز الهيكلي", "الجهاز الهضمي"], "optionsTr": ["Dolaşım sistemi", "Sinir sistemi", "İskelet sistemi", "Sindirim sistemi"], "correct": 0 },
      { "q": "In which school subject would you study the Ottoman Empire?", "qAr": "في أي مادة دراسية تدرس الإمبراطورية العثمانية؟", "qTr": "Osmanlı Devleti'ni hangi ders kapsamında öğrenirsiniz?", "options": ["History", "Music", "Art", "Sports"], "optionsAr": ["التاريخ", "الموسيقى", "الفن", "الرياضة"], "optionsTr": ["Tarih", "Müzik", "Resim", "Spor"], "correct": 0 },
      { "q": "Which fraction is equal to 0.5?", "qAr": "أي كسر يساوي 0.5؟", "qTr": "Hangi kesir 0,5'e eşittir?", "options": ["1/2", "1/3", "1/8", "2/5"], "optionsAr": ["½", "⅓", "⅛", "2/5"], "optionsTr": ["1/2", "1/3", "1/8", "2/5"], "correct": 0 },
      { "q": "In a triangle, the sum of interior angles is ———.", "qAr": "مجموع الزوايا الداخلية للمثلث يساوي ———.", "qTr": "Bir üçgenin iç açıları toplamı ——— derecedir.", "options": ["180 degrees", "90 degrees", "360 degrees", "200 degrees"], "optionsAr": ["180 درجة", "90 درجة", "360 درجة", "200 درجة"], "optionsTr": ["180", "90", "360", "200"], "correct": 0 },
      { "q": "Photosynthesis in plants mainly occurs in the ———.", "qAr": "عملية التمثيل الضوئي في النباتات تحدث أساساً في ———.", "qTr": "Bitkilerde fotosentez en çok ——— gerçekleşir.", "options": ["leaves", "roots", "flowers", "seeds"], "optionsAr": ["الأوراق", "الجذور", "الأزهار", "البذور"], "optionsTr": ["yapraklarda", "köklerde", "çiçeklerde", "tohumlarda"], "correct": 0 }
    ]
  }
};