/* QUIZORA QUESTION BANK — BATCH 1 (with topic tags for weak-topic analytics) */

module.exports = {
  fun: {
    general: [
      {"q":"Where is the Eiffel Tower located?","qTr":"Eyfel Kulesi nerededir?","options":["Paris","London","Rome","Berlin"],"optionsTr":["Paris","Londra","Roma","Berlin"],"correct":0},
      {"q":"Which is the largest ocean on Earth?","qTr":"Dünyadaki en büyük okyanus hangisidir?","options":["Atlantic","Indian","Pacific","Arctic"],"optionsTr":["Atlantik","Hint","Pasifik","Arktik"],"correct":2},
      {"q":"How many continents are there?","qTr":"Kaç kıta vardır?","options":["5","6","7","8"],"correct":2},
      {"q":"What is the chemical formula of water?","qTr":"Suyun kimyasal formülü nedir?","options":["CO2","H2O","O2","NaCl"],"correct":1},
      {"q":"Which metal is liquid at room temperature?","qTr":"Oda sıcaklığında sıvı olan metal hangisidir?","options":["Gold","Mercury","Lead","Iron"],"optionsTr":["Altın","Cıva","Kurşun","Demir"],"correct":1},
      {"q":"Who painted the Mona Lisa?","qTr":"Mona Lisa’yı kim resmetti?","options":["Pablo Picasso","Leonardo da Vinci","Vincent van Gogh","Michelangelo"],"optionsTr":["Pablo Picasso","Leonardo da Vinci","Vincent van Gogh","Michelangelo"],"correct":1},
      {"q":"The Statue of Liberty was a gift from which country?","qTr":"Özgürlük Heykeli hangi ülkenin hediyesiydi?","options":["France","Britain","Spain","Italy"],"optionsTr":["Fransa","Britanya","İspanya","İtalya"],"correct":0},
      {"q":"Which animal is known as the King of the Jungle?","qTr":"Ormanın kralı olarak bilinen hayvan hangisidir?","options":["Tiger","Lion","Elephant","Wolf"],"optionsTr":["Kaplan","Aslan","Fil","Kurt"],"correct":1},
    ],
    movies: [
      {"q":"In which year was the movie Titanic released?","qTr":"Titanic filmi hangi yıl yayınlandı?","options":["1994","1997","2000","2003"],"correct":1},
      {"q":"Who played the Joker in The Dark Knight (2008)?","qTr":"Kara Şövalye’de (2008) Joker’i kim oynadı?","options":["Jack Nicholson","Jared Leto","Heath Ledger","Joaquin Phoenix"],"optionsTr":["Jack Nicholson","Jared Leto","Heath Ledger","Joaquin Phoenix"],"correct":2},
      {"q":"What was Pixar’s first feature film?","qTr":"Pixar’ın ilk uzun metraj filmi hangisiydi?","options":["Monsters Inc.","Toy Story","Finding Nemo","Cars"],"optionsTr":["Canavarlar Şirketi","Oyuncak Hikayesi","Nemo’yu Bulmak","Arabalar"],"correct":1},
      {"q":"Which song is the centerpiece of Disney’s Frozen?","qTr":"Disney’in Frozen filmindeki ünlü şarkı hangisidir?","options":["Let It Go","Hakuna Matata","Under the Sea","A Whole New World"],"optionsTr":["Let It Go","Hakuna Matata","Under the Sea","A Whole New World"],"correct":0},
      {"q":"Who directed Inception and The Dark Knight?","qTr":"Inception ve Kara Şövalye’yi kim yönetti?","options":["Steven Spielberg","Christopher Nolan","James Cameron","Ridley Scott"],"optionsTr":["Steven Spielberg","Christopher Nolan","James Cameron","Ridley Scott"],"correct":1},
      {"q":"The Lion King takes place on which continent?","qTr":"Aslan Kral hangi kıtada geçer?","options":["Asia","South America","Africa","Australia"],"optionsTr":["Asya","Güney Amerika","Afrika","Avustralya"],"correct":2},
      {"q":"What is the name of the moon in the movie Avatar?","qTr":"Avatar filmindeki ayın adı nedir?","options":["Endor","Pandora","Tatooine","Naboo"],"optionsTr":["Endor","Pandora","Tatooine","Naboo"],"correct":1},
      {"q":"What kind of creature is Shrek?","qTr":"Shrek ne tür bir yaratıktır?","options":["Troll","Ogre","Goblin","Giant"],"optionsTr":["Trol","Dev (Ogre)","Goblin","Dev"],"correct":1},
    ],
    sports: [
      {"q":"How many players does a football (soccer) team have on the pitch?","qTr":"Futbol takımının sahada kaç oyuncusu vardır?","options":["9","10","11","12"],"correct":2},
      {"q":"The Summer Olympics are held every how many years?","qTr":"Yaz Olimpiyatları kaç yılda bir düzenlenir?","options":["2","3","4","5"],"correct":2},
      {"q":"How high is a basketball hoop from the floor?","qTr":"Basketbol potası yerden kaç metrededir?","options":["2.44 m","3.05 m","3.50 m","2.75 m"],"correct":1},
      {"q":"Who scored the famous \"Hand of God\" goal?","qTr":"Ünlü 'Tanrının Eli' golünü kim attı?","options":["Pele","Diego Maradona","Zinedine Zidane","Lionel Messi"],"optionsTr":["Pele","Diego Maradona","Zinedine Zidane","Lionel Messi"],"correct":1},
      {"q":"What surface is Wimbledon played on?","qTr":"Wimbledon hangi zeminde oynanır?","options":["Clay","Grass","Hard court","Carpet"],"optionsTr":["Kil (toprak)","Çim","Sert zemin","Halı"],"correct":1},
      {"q":"The Tour de France is a competition in which sport?","qTr":"Tour de France hangi sporun yarışıdır?","options":["Running","Swimming","Cycling","Rowing"],"optionsTr":["Koşu","Yüzme","Bisiklet","Kürek"],"correct":2},
      {"q":"The FIFA World Cup is held every how many years?","qTr":"FIFA Dünya Kupası kaç yılda bir yapılır?","options":["2","3","4","5"],"correct":2},
      {"q":"How many players from one basketball team are on the court at once?","qTr":"Basketbolda bir takımdan aynı anda sahada kaç oyuncu bulunur?","options":["4","5","6","7"],"correct":1},
    ],
    science: [
      {"q":"What is the closest star to Earth?","qTr":"Dünya’ya en yakın yıldız hangisidir?","options":["Proxima Centauri","Sirius","The Sun","Polaris"],"optionsTr":["Proxima Centauri","Sirius","Güneş","Kutup Yıldızı"],"correct":2},
      {"q":"At sea level, water boils at what temperature?","qTr":"Deniz seviyesinde su kaç derecede kaynar?","options":["90°C","95°C","100°C","110°C"],"correct":2},
      {"q":"Which planet is called the Red Planet?","qTr":"Hangi gezegen 'Kızıl Gezegen' olarak anılır?","options":["Venus","Mars","Jupiter","Mercury"],"optionsTr":["Venüs","Mars","Jüpiter","Merkür"],"correct":1},
      {"q":"Bats find their way in the dark using what?","qTr":"Yarasalar karanlıkta neyi kullanarak yönlerini bulur?","options":["Smell","Echolocation","Infrared vision","Magnetism"],"optionsTr":["Koku","Ekolokasyon (ses yankısı)","Kızılötesi görme","Manyetizma"],"correct":1},
      {"q":"In which organelle does photosynthesis take place?","qTr":"Fotosentez hangi organelde gerçekleşir?","options":["Mitochondria","Nucleus","Chloroplast","Ribosome"],"optionsTr":["Mitokondri","Çekirdek","Kloroplast","Ribozom"],"correct":2},
      {"q":"What is the normal human body temperature?","qTr":"Normal insan vücut sıcaklığı kaçtır?","options":["33°C","35°C","37°C","39°C"],"correct":2},
      {"q":"Lightning is a discharge of what?","qTr":"Şimşek neyin boşalmasıdır?","options":["Heat","Electricity","Sound","Magnetism"],"optionsTr":["Isı","Elektrik","Ses","Manyetizma"],"correct":1},
      {"q":"The speed of light is approximately:","qTr":"Işık hızı yaklaşık olarak nekadardır?","options":["300,000 km/s","150,000 km/s","3,000 km/s","30,000 km/s"],"correct":0},
    ],
    history: [
      {"q":"The Great Pyramids are located in which country?","qTr":"Büyük Piramitler hangi ülkededir?","options":["Iraq","Egypt","Mexico","Sudan"],"optionsTr":["Irak","Mısır","Meksika","Sudan"],"correct":1},
      {"q":"The Great Wall is in which country?","qTr":"Çin Seddi hangi ülkededir?","options":["Japan","India","China","Mongolia"],"optionsTr":["Japonya","Hindistan","Çin","Moğolistan"],"correct":2},
      {"q":"World War I took place in which years?","qTr":"Birinci Dünya Savaşı hangi yıllar arasında oldu?","options":["1914-1918","1939-1945","1905-1910","1920-1925"],"correct":0},
      {"q":"Who was the first person to walk on the Moon?","qTr":"Ay’a ilk ayak basan kişi kimdir?","options":["Yuri Gagarin","Buzz Aldrin","Neil Armstrong","Michael Collins"],"optionsTr":["Yuri Gagarin","Buzz Aldrin","Neil Armstrong","Michael Collins"],"correct":2},
      {"q":"Who invented the printing press?","qTr":"Matbaayı kim icat etti?","options":["Gutenberg","Edison","Bell","Newton"],"optionsTr":["Gutenberg","Edison","Bell","Newton"],"correct":0},
      {"q":"In which year did the Titanic sink?","qTr":"Titanic hangi yıl battı?","options":["1905","1912","1918","1922"],"correct":1},
      {"q":"In which year did World War II end?","qTr":"İkinci Dünya Savaşı hangi yıl bitti?","options":["1943","1944","1945","1946"],"correct":2},
      {"q":"What was the language of the ancient Romans?","qTr":"Eski Romalıların dili hangisiydi?","options":["Greek","Latin","Italian","Aramaic"],"optionsTr":["Yunanca","Latince","İtalyanca","Aramice"],"correct":1},
    ],
    family: [
      {"q":"How many dwarfs are there in Snow White?","qTr":"Pamuk Prenses’ten kaç cüce vardır?","options":["5","6","7","8"],"correct":2},
      {"q":"What is the name of Mickey Mouse’s dog?","qTr":"Mickey Mouse’un köpeğinin adı nedir?","options":["Goofy","Pluto","Donald","Scooby"],"optionsTr":["Goofy","Pluto","Donald","Scooby"],"correct":1},
      {"q":"What is Spider-Man’s real name?","qTr":"Örümcek Adam’ın gerçek adı nedir?","options":["Bruce Wayne","Peter Parker","Clark Kent","Tony Stark"],"optionsTr":["Bruce Wayne","Peter Parker","Clark Kent","Tony Stark"],"correct":1},
      {"q":"What kind of fish is Nemo?","qTr":"Nemo ne tür bir balıktır?","options":["Angel fish","Clownfish","Goldfish","Puffer fish"],"optionsTr":["Melek balığı","Palyaço balığı","Japon balığı","Balon balığı"],"correct":1},
      {"q":"Which school does Harry Potter attend?","qTr":"Harry Potter hangi okula gider?","options":["Durmstrang","Hogwarts","Beauxbatons","Ilvermorny"],"optionsTr":["Durmstrang","Hogwarts","Beauxbatons","Ilvermorny"],"correct":1},
      {"q":"Who is Shrek’s loyal best friend?","qTr":"Shrek’in sadık en iyi arkadaşı kimdir?","options":["Puss in Boots","Donkey","Lord Farquaad","Pinocchio"],"optionsTr":["Çizmeli Kedi","Eşek","Lord Farquaad","Pinokyo"],"correct":1},
      {"q":"How many colors are in a rainbow?","qTr":"Gökkuşağında kaç renk vardır?","options":["5","6","7","8"],"correct":2},
      {"q":"What animals are Tom and Jerry?","qTr":"Tom ve Jerry hangi hayvanlardır?","options":["Dog and cat","Cat and mouse","Mouse and bird","Cat and bird"],"optionsTr":["Köpek ve kedi","Kedi ve fare","Fare ve kuş","Kedi ve kuş"],"correct":1},
    ],
    music: [
      {"q":"Which condition affected Beethoven’s career as a composer?","qTr":"Hangi rahatsızlık Beethoven’ın besteci kariyerini etkiledi?","options":["Blindness","Deafness","Asthma","Arthritis"],"optionsTr":["Körlük","Sağırlık","Astım","Artrit"],"correct":1},
      {"q":"How many strings does a standard guitar have?","qTr":"Standart bir gitarda kaç tel vardır?","options":["4","5","6","7"],"correct":2},
      {"q":"Which band performed Bohemian Rhapsody?","qTr":"'Bohemian Rhapsody' şarkısını hangi grup söyledi?","options":["The Beatles","Queen","Pink Floyd","Rolling Stones"],"optionsTr":["The Beatles","Queen","Pink Floyd","Rolling Stones"],"correct":1},
      {"q":"How many keys does a standard piano have?","qTr":"Standart bir piyanoda kaç tuş vardır?","options":["76","84","88","92"],"correct":2},
      {"q":"How many strings does a violin have?","qTr":"Kemanda kaç tel vardır?","options":["3","4","5","6"],"correct":1},
      {"q":"Who is known as the King of Pop?","qTr":"'Pop’un Kralı' olarak kim bilinir?","options":["Elvis Presley","Michael Jackson","Prince","Freddie Mercury"],"optionsTr":["Elvis Presley","Michael Jackson","Prince","Freddie Mercury"],"correct":1},
      {"q":"Which Turkish singer is nicknamed the \"Prince of the Bosphorus\"?","qTr":"Hangi Türk şarkıcı 'Boğazın Prensi' olarak anılır?","options":["Tarkan","İbrahim Tatlıses","Mustafa Sandal","Kenan Doğulu"],"optionsTr":["Tarkan","İbrahim Tatlıses","Mustafa Sandal","Kenan Doğulu"],"correct":0},
      {"q":"Who wrote the lyrics of the Turkish National Anthem?","qTr":"Türk İstiklal Marşı’nın sözlerini kim yazdı?","options":["Namık Kemal","Mehmet Akif Ersoy","Tevfik Fikret","Yahya Kemal"],"optionsTr":["Namık Kemal","Mehmet Akif Ersoy","Tevfik Fikret","Yahya Kemal"],"correct":1},
    ],
    geography: [
      {"q":"Which is the largest hot desert in the world?","qTr":"Dünyanın en büyük sıcak çölü hangisidir?","options":["Gobi","Kalahari","Sahara","Atacama"],"optionsTr":["Gobi","Kalahari","Sahra","Atacama"],"correct":2},
      {"q":"The Nile River flows through which continent?","qTr":"Nil Nehri hangi kıtadan geçer?","options":["Asia","Africa","Europe","South America"],"optionsTr":["Asya","Afrika","Avrupa","Güney Amerika"],"correct":1},
      {"q":"What is the capital of Japan?","qTr":"Japonya’nın başkenti neresidir?","options":["Osaka","Kyoto","Tokyo","Seoul"],"optionsTr":["Osaka","Kyoto","Tokyo","Seul"],"correct":2},
      {"q":"Which is the highest mountain on Earth?","qTr":"Dünyanın en yüksek dağı hangisidir?","options":["K2","Everest","Kilimanjaro","Mont Blanc"],"optionsTr":["K2","Everest","Kilimanjaro","Mont Blanc"],"correct":1},
      {"q":"Kangaroos are native to which country?","qTr":"Kangurular hangi ülkeye özgüdür?","options":["Africa","Australia","Brazil","India"],"optionsTr":["Afrika","Avustralya","Brezilya","Hindistan"],"correct":1},
      {"q":"The Amazon rainforest is mainly in which continent?","qTr":"Amazon yağmur ormanları ağırlıklı olarak hangi kıtadadır?","options":["Africa","Asia","South America","Oceania"],"optionsTr":["Afrika","Asya","Güney Amerika","Okyanusya"],"correct":2},
      {"q":"Which country’s flag features a maple leaf?","qTr":"Hangi ülkenin bayrağında akçaağaç yaprağı vardır?","options":["USA","Canada","Norway","Switzerland"],"optionsTr":["ABD","Kanada","Norveç","İsviçre"],"correct":1},
      {"q":"Niagara Falls lies on the border between the USA and which country?","qTr":"Niagara Şelalesi ABD ile hangi ülke arasındadır?","options":["Mexico","Canada","Cuba","UK"],"optionsTr":["Meksika","Kanada","Küba","İngiltere"],"correct":1},
    ],
    tech: [
      {"q":"What is HTML used for?","qTr":"HTML ne için kullanılır?","options":["Building web pages","Editing photos","Making calls","Playing music"],"optionsTr":["Web sayfası oluşturma","Fotoğraf düzenleme","Arama yapma","Müzik çalma"],"correct":0},
      {"q":"In which year was the first iPhone released?","qTr":"İlk iPhone hangi yıl çıktı?","options":["2005","2007","2009","2010"],"correct":1},
      {"q":"Which company owns Android?","qTr":"Android hangi şirkete aittir?","options":["Apple","Microsoft","Google","Samsung"],"optionsTr":["Apple","Microsoft","Google","Samsung"],"correct":2},
      {"q":"What is often called the brain of the computer?","qTr":"Bilgisayarın beyni olarak ne anılır?","options":["RAM","CPU","GPU","Hard disk"],"optionsTr":["RAM","CPU (işlemci)","GPU","Hard disk"],"correct":1},
      {"q":"What type of memory is RAM?","qTr":"RAM ne tür bir bellektir?","options":["Permanent","Volatile (temporary)","Optical","Magnetic tape"],"optionsTr":["Kalıcı","Geçici (uçucu)","Optik","Manyetik bant"],"correct":1},
      {"q":"Wi-Fi is a technology for what?","qTr":"Wi-Fi hangi amaçla kullanılan bir teknolojidir?","options":["Wireless networking","Charging batteries","Printing","Cooling CPUs"],"optionsTr":["Kablosuz ağ bağlantısı","Batarya şarjı","Yazdırma","İşlemci soğutma"],"correct":0},
      {"q":"Python is what?","qTr":"Python nedir?","options":["A snake only","A programming language","A robot","A chip"],"optionsTr":["Sadece bir yılan","Bir programlama dili","Bir robot","Bir çip"],"correct":1},
      {"q":"In an email address, what does the @ symbol separate?","qTr":"E-posta adresinde @ sembolü neyi ayırır?","options":["User and domain","Two users","Password and server","Time zones"],"optionsTr":["Kullanıcı ve alan adı","İki kullanıcıyı","Şifre ve sunucu","Saat dilimleri"],"correct":0},
    ],
    islam: [
      {"q":"How many pillars does Islam have?","qTr":"İslam’ın kaç şartı (temeli) vardır?","options":["3","4","5","6"],"correct":2},
      {"q":"How many surahs are in the Quran?","qTr":"Kur’an’da kaç sure vardır?","options":["110","112","114","116"],"correct":2},
      {"q":"Which month do Muslims fast in?","qTr":"Müslümanlar hangi ayda oruç tutar?","options":["Shawwal","Ramadan","Muharram","Rajab"],"optionsTr":["Şevval","Ramazan","Muharrem","Recep"],"correct":1},
      {"q":"The Kaaba is located in which city?","qTr":"Kaabe hangi şehirdedir?","options":["Medina","Mecca","Jerusalem","Cairo"],"optionsTr":["Medine","Mekke","Kudüs","Kahire"],"correct":1},
      {"q":"How many daily prayers are there in Islam?","qTr":"İslam’da günde kaç vakit farz namaz vardır?","options":["3","4","5","6"],"correct":2},
      {"q":"In which city was Prophet Muhammad born?","qTr":"Peygamber Efendimiz hangi şehirde doğdu?","options":["Medina","Taif","Mecca","Damascus"],"optionsTr":["Medine","Taif","Mekke","Şam"],"correct":2},
      {"q":"In which month is Hajj performed?","qTr":"Hac hangi ayda yapılır?","options":["Ramadan","Dhul-Hijjah","Safar","Shaban"],"optionsTr":["Ramazan","Zilhicce","Safer","Şaban"],"correct":1},
      {"q":"What is the first surah of the Quran?","qTr":"Kur’an’ın ilk suresi hangisidir?","options":["Al-Baqarah","Al-Fatiha","Al-Ikhlas","An-Nas"],"optionsTr":["Bakara","Fatiha","İhlas","Nas"],"correct":1},
    ],
  },

  exam: {
    yks: [
      {"q":"What is 15% of 240?","qTr":"240’ın yüzde 15’i kaçtır?","options":["34","36","38","40"],"correct":1,"topic":"matematik"},
      {"q":"What is 3 to the power of 4?","qTr":"3 üzeri 4 kaçtır?","options":["64","81","121","27"],"correct":1,"topic":"matematik"},
      {"q":"What is the square root of 144?","qTr":"144’ün karekökü kaçtır?","options":["10","11","12","14"],"correct":2,"topic":"matematik"},
      {"q":"If 2x + 5 = 17, what is x?","qTr":"2x + 5 = 17 ise x kaçtır?","options":["5","6","7","8"],"correct":1,"topic":"matematik"},
      {"q":"25% of a number is 45. What is the number?","qTr":"Bir sayının yüzde 25’i 45 ise bu sayı kaçtır?","options":["135","160","180","225"],"correct":2,"topic":"matematik"},
      {"q":"What is the greatest common divisor (GCD) of 24 and 36?","qTr":"24 ve 36’nın en büyük ortak böleni (EBOB) kaçtır?","options":["6","8","12","18"],"correct":2,"topic":"matematik"},
      {"q":"What is the least common multiple (LCM) of 6 and 8?","qTr":"6 ve 8’in en küçük ortak katı (EKOK) kaçtır?","options":["16","24","36","48"],"correct":1,"topic":"matematik"},
      {"q":"Two angles of a triangle are 50° and 60°. What is the third angle?","qTr":"Bir üçgenin iki açısı 50° ve 60° ise üçüncü açı kaç derecedir?","options":["60°","70°","80°","90°"],"correct":1,"topic":"matematik"},
      {"q":"What is the value of |-7|?","qTr":"|-7| ifadesinin değeri kaçtır?","options":["-7","7","0","49"],"correct":1,"topic":"matematik"},
      {"q":"What is 5! (5 factorial)?","qTr":"5! (beş faktöriyel) kaçtır?","options":["25","60","120","720"],"correct":2,"topic":"matematik"},
      {"q":"What is the area of a circle with radius 3? (A = πr²)","qTr":"Yarıçapı 3 olan dairenin alanı kaçtır? (A = πr²)","options":["3π","6π","9π","12π"],"correct":2,"topic":"matematik"},
      {"q":"In an arithmetic sequence the first term is 3 and the common difference is 4. What is the 5th term?","qTr":"İlk terimi 3, ortak farkı 4 olan aritmetik dizide 5. terim kaçtır?","options":["19","20","23","24"],"correct":0,"topic":"matematik"},
      {"q":"What is the SI unit of force?","qTr":"Kuvvetin SI birimi nedir?","options":["Joule","Newton","Watt","Pascal"],"optionsTr":["Joule","Newton","Watt","Pascal"],"correct":1,"topic":"fizik"},
      {"q":"A car travels 120 km in 2 hours. What is its average speed?","qTr":"Bir araba 2 saatte 120 km yol gidiyor. Ortalama hızı kaçtır?","options":["50 km/h","60 km/h","70 km/h","240 km/h"],"optionsTr":["50 km/sa","60 km/sa","70 km/sa","240 km/sa"],"correct":1,"topic":"fizik"},
      {"q":"The gravitational acceleration on Earth is approximately:","qTr":"Yer çekimi ivmesi yaklaşık olarak kaçtır?","options":["5.8 m/s²","9.8 m/s²","12 m/s²","98 m/s²"],"optionsTr":["5,8 m/s²","9,8 m/s²","12 m/s²","98 m/s²"],"correct":1,"topic":"fizik"},
      {"q":"According to Newton’s first law, an object at rest stays at rest unless what acts on it?","qTr":"Newton’un birinci yasasına göre durgun hâldeki cisim, ne üzerine etki etmedikçe durgun kalır?","options":["Gravity","A net force","Friction","Air"],"optionsTr":["Yer çekimi","Net bir kuvvet","Sürtünme","Hava"],"correct":1,"topic":"fizik"},
      {"q":"What is the SI unit of power?","qTr":"Gücün SI birimi nedir?","options":["Newton","Watt","Joule","Volt"],"optionsTr":["Newton","Watt","Joule","Volt"],"correct":1,"topic":"fizik"},
      {"q":"An object has a mass of 200 g and a volume of 50 cm³. What is its density?","qTr":"Kütlesi 200 g, hacmi 50 cm³ olan cismin özkütleşi kaçtır?","options":["2 g/cm³","4 g/cm³","10 g/cm³","0.25 g/cm³"],"optionsTr":["2 g/cm³","4 g/cm³","10 g/cm³","0,25 g/cm³"],"correct":1,"topic":"fizik"},
      {"q":"A force of 10 N moves an object 5 m in the direction of the force. How much work is done?","qTr":"10 N’luk kuvvet cismi kuvvet yönünde 5 m hareket ettiriyor. Yapılan iş kaç joule’dür?","options":["2 J","15 J","50 J","100 J"],"optionsTr":["2 J","15 J","50 J","100 J"],"correct":2,"topic":"fizik"},
      {"q":"The speed of sound in air is approximately:","qTr":"Sesin havadaki hızı yaklaşık olarak kaçtır?","options":["120 m/s","340 m/s","700 m/s","300,000 km/s"],"optionsTr":["120 m/s","340 m/s","700 m/s","300.000 km/s"],"correct":1,"topic":"fizik"},
      {"q":"How many hydrogen atoms are in one water molecule (H2O)?","qTr":"Bir su molekülünde (H2O) kaç hidrojen atomu vardır?","options":["1","2","3","4"],"correct":1,"topic":"kimya"},
      {"q":"The atomic number of an element equals the number of its:","qTr":"Bir elementin atom numarası onun hangi tanecik sayısına eşittir?","options":["Neutrons","Protons","Electron shells","Nucleons"],"optionsTr":["Nötronları","Protonları","Elektron kabukları","Nükleonları"],"correct":1,"topic":"kimya"},
      {"q":"NaCl is commonly known as:","qTr":"NaCl halk arasında ne olarak bilinir?","options":["Sugar","Table salt","Baking soda","Lime"],"optionsTr":["Şeker","Sofra tuzu","Kabartma tozu","Kireç"],"correct":1,"topic":"kimya"},
      {"q":"A solution with pH 5 is:","qTr":"pH’ı 5 olan bir çözelti nasıldır?","options":["Basic","Acidic","Neutral","Salty"],"optionsTr":["Bazik","Asidik","Nötr","Tuzlu"],"correct":1,"topic":"kimya"},
      {"q":"Which gas makes up about 78% of Earth’s atmosphere?","qTr":"Dünya atmosferinin yaklaşık yüzde 78’ini hangi gaz oluşturur?","options":["Oxygen","Carbon dioxide","Nitrogen","Argon"],"optionsTr":["Oksijen","Karbondioksit","Azot","Argon"],"correct":2,"topic":"kimya"},
      {"q":"The chemical symbol Fe represents which element?","qTr":"Fe sembolü hangi elementi gösterir?","options":["Fluorine","Iron","Francium","Fermium"],"optionsTr":["Flor","Demir","Fransiyum","Fermiyum"],"correct":1,"topic":"kimya"},
      {"q":"How many particles are in one mole of a substance (Avogadro’s number)?","qTr":"1 mol maddede kaç tanecik vardır? (Avogadro sayısı)","options":["6.02 × 10²³","3.14 × 10²³","6.02 × 10¹⁹","9.8 × 10²³"],"optionsTr":["6,02 × 10²³","3,14 × 10²³","6,02 × 10¹⁹","9,8 × 10²³"],"correct":0,"topic":"kimya"},
      {"q":"The noble gases are found in which group of the periodic table?","qTr":"Soy (asal) gazlar periyodik tablonun hangi grubundadır?","options":["1A","2A","7A","8A"],"optionsTr":["1A","2A","7A","8A"],"correct":3,"topic":"kimya"},
      {"q":"Which organelle is called the powerhouse of the cell?","qTr":"Hangi organel hücrenin enerji santrali olarak anılır?","options":["Nucleus","Mitochondria","Ribosome","Vacuole"],"optionsTr":["Çekirdek","Mitokondri","Ribozom","Koful"],"correct":1,"topic":"biyoloji"},
      {"q":"What are the products of photosynthesis?","qTr":"Fotosentez sonucunda hangi ürünler oluşur?","options":["CO2 and water","Glucose and oxygen","Protein and fat","Salt and water"],"optionsTr":["CO2 ve su","Glikoz ve oksijen","Protein ve yağ","Tuz ve su"],"correct":1,"topic":"biyoloji"},
      {"q":"What is the basic structural unit of all living things?","qTr":"Tüm canlıların temel yapı birimi nedir?","options":["Tissue","Cell","Organ","Atom"],"optionsTr":["Doku","Hücre","Organ","Atom"],"correct":1,"topic":"biyoloji"},
      {"q":"How many chromosomes does a normal human body cell have?","qTr":"Normal bir insan vücut hücresinde kaç kromozom vardır?","options":["23","42","46","48"],"correct":2,"topic":"biyoloji"},
      {"q":"Which blood cells transport oxygen in humans?","qTr":"İnsanda oksijen taşıyan kan hücreleri hangileridir?","options":["White blood cells","Red blood cells","Platelets","Plasma cells"],"optionsTr":["Akyuvar","Alyuvar","Kan pulcukları","Plazma hücreleri"],"correct":1,"topic":"biyoloji"},
      {"q":"Plant cell walls are made mainly of which substance?","qTr":"Bitki hücre duvarları ağırlıklı olarak hangi maddeden yapılmıştır?","options":["Starch","Cellulose","Protein","Chitin"],"optionsTr":["Nişasta","Selüloz","Protein","Kitin"],"correct":1,"topic":"biyoloji"},
      {"q":"Which molecule carries genetic information?","qTr":"Kalıtsal bilgiyi taşıyan molekül hangisidir?","options":["RNA","DNA","ATP","Protein"],"optionsTr":["RNA","DNA","ATP","Protein"],"correct":1,"topic":"biyoloji"},
      {"q":"The chemical digestion of proteins in humans begins in the:","qTr":"İnsanda proteinlerin kimyasal sindirimi nerede başlar?","options":["Mouth","Stomach","Small intestine","Liver"],"optionsTr":["Ağız","Mide","İnce bağırsak","Karaciğer"],"correct":1,"topic":"biyoloji"},
      {"q":"On which date was the Republic of Türkiye proclaimed?","qTr":"Türkiye Cumhuriyeti hangi tarihte ilan edildi?","options":["23 April 1920","30 August 1922","29 October 1923","19 May 1919"],"optionsTr":["23 Nisan 1920","30 Ağustos 1922","29 Ekim 1923","19 Mayıs 1919"],"correct":2,"topic":"tarih"},
      {"q":"In which year did the Battle of Manzikert (Malazgirt) take place?","qTr":"Malazgirt Savaşı hangi yıl yapıldı?","options":["1071","1243","1453","1492"],"correct":0,"topic":"tarih"},
      {"q":"Who conquered Istanbul in 1453?","qTr":"İstanbul’u 1453’te fetheden padişah kimdir?","options":["Osman Bey","Yavuz Sultan Selim","Fatih Sultan Mehmed","Kanuni Sultan Süleyman"],"optionsTr":["Osman Bey","Yavuz Sultan Selim","Fatih Sultan Mehmed","Kanuni Sultan Süleyman"],"correct":2,"topic":"tarih"},
      {"q":"In which year was the Ottoman State founded?","qTr":"Osmanlı Devleti hangi yıl kuruldu?","options":["1071","1299","1326","1453"],"correct":1,"topic":"tarih"},
      {"q":"Which treaty replaced the Treaty of Sèvres?","qTr":"Sevr Antlaşması’nın yerine hangi antlaşma geçti?","options":["Treaty of Mudros","Treaty of Lausanne","Treaty of Mudanya","Treaty of Kars"],"optionsTr":["Mondros Antlaşması","Lozan Antlaşması","Mudanya Antlaşması","Kars Antlaşması"],"correct":1,"topic":"tarih"},
      {"q":"In which year was the first Ottoman constitution (Kanun-i Esasi) declared?","qTr":"Osmanlı’nın ilk anayasası Kanun-i Esasi hangi yıl ilan edildi?","options":["1839","1856","1876","1908"],"correct":2,"topic":"tarih"},
      {"q":"Which is the highest mountain in Türkiye?","qTr":"Türkiye’nin en yüksek dağı hangisidir?","options":["Erciyes","Uludağ","Ağrı Dağı","Cilo Dağı"],"optionsTr":["Erciyes","Uludağ","Ağrı Dağı","Cilo Dağı"],"correct":2,"topic":"coğrafya"},
      {"q":"Which is the longest river entirely within Türkiye?","qTr":"Tamamen Türkiye sınırları içindeki en uzun nehir hangisidir?","options":["Fırat","Kızılırmak","Dicle","Sakarya"],"optionsTr":["Fırat","Kızılırmak","Dicle","Sakarya"],"correct":1,"topic":"coğrafya"},
      {"q":"Which is the largest lake in Türkiye?","qTr":"Türkiye’nin en büyük gölü hangisidir?","options":["Tuz Gölü","Van Gölü","Beyşehir Gölü","Eğirdir Gölü"],"optionsTr":["Tuz Gölü","Van Gölü","Beyşehir Gölü","Eğirdir Gölü"],"correct":1,"topic":"coğrafya"},
      {"q":"The Bosphorus (İstanbul Boğazı) connects the Black Sea to which sea?","qTr":"İstanbul Boğazı Karadeniz’i hangi denize bağlar?","options":["Aegean Sea","Sea of Marmara","Mediterranean Sea","Red Sea"],"optionsTr":["Ege Denizi","Marmara Denizi","Akdeniz","Kızıl Deniz"],"correct":1,"topic":"coğrafya"},
      {"q":"What is the capital of Türkiye?","qTr":"Türkiye’nin başkenti neresidir?","options":["Istanbul","Izmir","Ankara","Bursa"],"optionsTr":["İstanbul","İzmir","Ankara","Bursa"],"correct":2,"topic":"coğrafya"},
      {"q":"In the sentence \"Kalem masanın üstünde\" (The pen is on the table), what does the word \"kalem\" (pen) express?","qTr":"'Kalem masanın üstünde' cümlesinde 'kalem' sözcüğü ne bildirir?","options":["An action (fiil)","A thing / noun (isim)","A feeling","A time"],"optionsTr":["Bir iş (fiil)","Bir varlık (isim)","Bir duygu","Bir zaman"],"correct":1,"topic":"türkçe"},
      {"q":"The idiom \"Etekleri zil çalmak\" means:","qTr":"'Etekleri zil çalmak' deyiminin anlamı nedir?","options":["To be very sad","To be very happy/excited","To be very angry","To be very tired"],"optionsTr":["Çok üzülmek","Çok sevinmek","Çok öfkelenmek","Çok yorulmak"],"correct":1,"topic":"türkçe"},
      {"q":"Which is written correctly?","qTr":"Hangisi doğru yazılmıştır?","options":["herşey","her şey","herşeyi","her-şey"],"optionsTr":["herşey","her şey","herşeyi","her-şey"],"correct":1,"topic":"türkçe"},
      {"q":"Which word is an \"eş sesli\" (homonym, one word with two meanings)?","qTr":"Aşağıdakilerden hangisi eş sesli (sesteş) bir sözcüktür?","options":["Yüz","Kalem","Okul","Masa"],"optionsTr":["Yüz","Kalem","Okul","Masa"],"correct":0,"topic":"türkçe"},
      {"q":"The proverb \"Damlaya damlaya göl olur\" teaches:","qTr":"'Damlaya damlaya göl olur' atasözü bize neyi öğretir?","options":["Small savings become big","Water is life","Lakes are deep","Rain is needed"],"optionsTr":["Az az biriken çok olur","Su hayattır","Göller derindir","Yağmur gerekir"],"correct":0,"topic":"türkçe"},
    ],
  },
};
